C10a2: algo.c C10a2.c 
	gcc -std=c99 -Wall -Werror algo.c C10a2.c -o autoSAT

C10a3: algo.c C10a3.c 
	gcc -std=c99 -Wall -Werror algo.c C10a3.c -o C10a3

K5_5: algo.c K5_5
	gcc -std=c99 -Wall -Werror algo.c K5_5.c -o  K5_5

K7_11: algo.c K7_11.c 
	gcc -std=c99 -Wall -Werror algo.c K7_11.c -o K7_11

Petersen: algo.c Petersen.c 
	gcc -std=c99 -Wall -Werror algo.c Petersen.c -o Petersen
